### ISSUE TITLE
Всем русским сообществом ожидаем антипинг.

### ISSUE THREAD

**Issue by FalletFallet** [axblk/teeworlds#50]
Разработчик мне так лень переводить тебе то , что я сейчас буду писать. Мы уже довольно долго ждем хороший антипинг. Не только мы русские но и йорданцы и другие пользователи с пингом выше 60. В чем проблема взять открытый код антипинга из DDnet и просто ctr+c и ctr+v в твой код? Он же идеально работает и получше чем тот который создал ты. Просто сделай так как я написал выше пока делаешь новую "улучшенную" версию. Благодарю за прочтения Ваш Fallet лучший игрок в TeeWar

**Comment by axblk** [comment]
Please write in english, use Googe translator or whatever but please only open issues in english...
The physics in DDNet and Teeworlds 0.7 differ in several aspects and the DDNet physics code is pretty buggy and ugly.
Even taking the whole DDNet antiping code would require some work as a lot in the codebase has changed from 0.6 to 0.7.
I am aware that in the current state 0.7 antiping is far below the capabilities of DDNet, but due to a lack of time I am not working on anything Teeworlds related at all.
